### ISSUE TITLE
How do i fix this ?

### ISSUE THREAD

**Issue by pidugusundeep** [alperencubuk/Copy-Move-Forgery-Detection#2]
`
cv2.error: OpenCV(3.4.2) /io/opencv/modules/imgproc/src/color.hpp:253: error: (-215:Assertion failed) VScn::contains(scn) && VDcn::contains(dcn) && VDepth::contains(depth) in function 'CvtHelper'
`

**Comment by alperencubuk** [comment]
Here is my terminal history:
```
git clone https://github.com/alperencubuk/Copy-Move-Forgery-Detection.git
cd Copy-Move-Forgery-Detection
pip install opencv-python
python3 forgery_detection.py
```
You should install opencv and numpy (pip install opencv-python command installs both).
Here is my pip freeze output:
```
numpy==1.17.4
opencv-python==4.1.1.26
```
And python -V output:
`Python 3.7.4`

So try to use this versions. Maybe other versions has some incompatible things.
